name: Daily Earth2Studio Inference

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}



permissions:
  contents: write  # allow workflow to push changes
  pages: write


jobs:
  run-inference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean previous outputs
        run: |
          rm -f docs/outputs/*
          mkdir -p docs/outputs
          wget -O docs/outputs/BFS_rain.gif "https://nwp.imd.gov.in/gfs_ar/00/24hGFS1534rain.gif"

      - name: Run daily Earth2Studio script
        env:
          NOAA_KEY: ${{ secrets.NOAA_KEY }}
          OTHER_ENV: ${{ secrets.OTHER_ENV }}
        run: |
          python scripts/daily_inference.py

      - name: Commit & push outputs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A docs/outputs/
          if ! git diff --cached --quiet; then
            git commit -m "Update daily forecast"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No files to commit"
          fi
      - name: Wait for commit propagation
        run: sleep 10

      - name: Trigger GitHub Pages rebuild
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds
